# Generated by Django 3.0.4 on 2020-04-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('notebook', 'notebook'), ('tablet', 'tablet'), ('mobile', 'mobile'), ('pc', 'pc')], default='mobile', max_length=20),
        ),
    ]
