# Generated by Django 3.0.4 on 2020-04-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200405_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
