# Generated by Django 3.0.4 on 2020-04-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200405_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('pc', 'pc'), ('mobile', 'mobile'), ('tablet', 'tablet'), ('notebook', 'notebook')], default='mobile', max_length=20),
        ),
    ]
